# This is a basic workflow to help you get started with Actions
name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t countdigi/snptk:${GITHUB_SHA:0:10} .
    - run: docker run -it countdigi/snptk snptk --help
