# This is a basic workflow to help you get started with Actions
name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo ${GITHUB_SHA:0:10}

      - run: docker build -t ${{ secrets.DOCKER_USER }}/snptk .

      - run: docker run ${{ secrets.DOCKER_USER}}/snptk snptk --help

      - run: |
          docker tag ${{ secrets.DOCKER_USER }}/snptk ${{ secrets.DOCKER_USER }}/snptk:${GITHUB_SHA:0:10}
          docker tag ${{ secrets.DOCKER_USER }}/snptk ${{ secrets.DOCKER_USER }}/snptk:latest

      - run: docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker push ${{ secrets.DOCKER_USER }}/snptk:${GITHUB_SHA:0:10}
          docker push ${{ secrets.DOCKER_USER }}/snptk:latest
