# This is a basic workflow to help you get started with Actions
name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: /bin/ls -la
    - run: docker version

